### ISSUE TITLE
Update for latest development version of Frog

### ISSUE THREAD

**Issue by proycon** [proycon/python-frog#20]
There have been some changes in the API interface so the current git master tree of python-frog doesn't compile against Frog anymore, the binding needs to adapt (arose from LanguageMachines/ucto#82)

**Comment by kosloot** [comment]
I added a FrogAPI constructor, which should help a lot:
```
FrogAPI::FrogAPI( const TiCC::Configuration& configuration,
		  TiCC::LogStream *err_log,
		  TiCC::LogStream *dbg_log ):
```

**Comment by proycon** [comment]
Thanks!

**Comment by kosloot** [comment]
off-course it's completely  untested :)

**Comment by proycon** [comment]
Running into a segfault, I wonder if some other parts changed too... will have to investigate further:

```
(gdb) bt
#0  0x00007ffff5eed4e0 in std::ostream::sentry::sentry (this=0x7fffffffbac0, __os=...) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:51
#1  0x00007ffff5eee4a7 in std::ostream::_M_insert<unsigned long> (this=this@entry=0x0, __v=__v@entry=1) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream.tcc:66
#2  0x00007ffff690367f in std::ostream::operator<< (__n=1, this=0x0) at /usr/include/c++/10.2.0/ostream:170
#3  FrogAPI::show_results (fd=..., os=..., this=0x5555558ff220) at FrogAPI.cxx:2231
#4  FrogAPI::show_results (this=0x5555558ff220, os=..., fd=...) at FrogAPI.cxx:2209
#5  0x00007ffff6904e21 in FrogAPI::run_text_engine (this=0x5555558ff220, infilename=..., os=...) at FrogAPI.cxx:2684
#6  0x00007ffff690a7e5 in FrogAPI::FrogFile (this=0x5555558ff220, infilename="/tmp//frogurRsdY") at FrogAPI.cxx:2723
#7  0x00007ffff690af0f in FrogAPI::Frogtostringfromfile (this=0x5555558ff220, infilename=...) at FrogAPI.cxx:1831
#8  0x00007ffff690b453 in FrogAPI::Frogtostring (this=0x5555558ff220, s="Dit is een test") at FrogAPI.cxx:1814
#9  0x00007ffff6a64449 in __pyx_pf_4frog_4Frog_2process_raw (__pyx_v_text=<optimized out>, __pyx_v_self=0x555555693920) at frog_wrapper.cpp:4323
#10 __pyx_pw_4frog_4Frog_3process_raw (__pyx_v_self=0x555555693920, __pyx_v_text=<optimized out>) at frog_wrapper.cpp:4276
```

**Comment by proycon** [comment]
This is fixed now
